/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnternehmenRouteImport } from './routes/unternehmen'
import { Route as ProduktTwoRouteImport } from './routes/produkt-two'
import { Route as ProduktRouteImport } from './routes/produkt'
import { Route as MarktRouteImport } from './routes/markt'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnternehmenIndexRouteImport } from './routes/unternehmen.index'
import { Route as UnternehmenTeamRouteImport } from './routes/unternehmen.team'
import { Route as ApiIngestRouteImport } from './routes/api/ingest'
import { Route as ApiPublicSensorRouteImport } from './routes/api/public/sensor'
import { Route as ApiPublicLatestRouteImport } from './routes/api/public/latest'

const UnternehmenRoute = UnternehmenRouteImport.update({
  id: '/unternehmen',
  path: '/unternehmen',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduktTwoRoute = ProduktTwoRouteImport.update({
  id: '/produkt-two',
  path: '/produkt-two',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduktRoute = ProduktRouteImport.update({
  id: '/produkt',
  path: '/produkt',
  getParentRoute: () => rootRouteImport,
} as any)
const MarktRoute = MarktRouteImport.update({
  id: '/markt',
  path: '/markt',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnternehmenIndexRoute = UnternehmenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UnternehmenRoute,
} as any)
const UnternehmenTeamRoute = UnternehmenTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => UnternehmenRoute,
} as any)
const ApiIngestRoute = ApiIngestRouteImport.update({
  id: '/api/ingest',
  path: '/api/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSensorRoute = ApiPublicSensorRouteImport.update({
  id: '/api/public/sensor',
  path: '/api/public/sensor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLatestRoute = ApiPublicLatestRouteImport.update({
  id: '/api/public/latest',
  path: '/api/public/latest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/markt': typeof MarktRoute
  '/produkt': typeof ProduktRoute
  '/produkt-two': typeof ProduktTwoRoute
  '/unternehmen': typeof UnternehmenRouteWithChildren
  '/api/ingest': typeof ApiIngestRoute
  '/unternehmen/team': typeof UnternehmenTeamRoute
  '/unternehmen/': typeof UnternehmenIndexRoute
  '/api/public/latest': typeof ApiPublicLatestRoute
  '/api/public/sensor': typeof ApiPublicSensorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/markt': typeof MarktRoute
  '/produkt': typeof ProduktRoute
  '/produkt-two': typeof ProduktTwoRoute
  '/api/ingest': typeof ApiIngestRoute
  '/unternehmen/team': typeof UnternehmenTeamRoute
  '/unternehmen': typeof UnternehmenIndexRoute
  '/api/public/latest': typeof ApiPublicLatestRoute
  '/api/public/sensor': typeof ApiPublicSensorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/markt': typeof MarktRoute
  '/produkt': typeof ProduktRoute
  '/produkt-two': typeof ProduktTwoRoute
  '/unternehmen': typeof UnternehmenRouteWithChildren
  '/api/ingest': typeof ApiIngestRoute
  '/unternehmen/team': typeof UnternehmenTeamRoute
  '/unternehmen/': typeof UnternehmenIndexRoute
  '/api/public/latest': typeof ApiPublicLatestRoute
  '/api/public/sensor': typeof ApiPublicSensorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/markt'
    | '/produkt'
    | '/produkt-two'
    | '/unternehmen'
    | '/api/ingest'
    | '/unternehmen/team'
    | '/unternehmen/'
    | '/api/public/latest'
    | '/api/public/sensor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/markt'
    | '/produkt'
    | '/produkt-two'
    | '/api/ingest'
    | '/unternehmen/team'
    | '/unternehmen'
    | '/api/public/latest'
    | '/api/public/sensor'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/markt'
    | '/produkt'
    | '/produkt-two'
    | '/unternehmen'
    | '/api/ingest'
    | '/unternehmen/team'
    | '/unternehmen/'
    | '/api/public/latest'
    | '/api/public/sensor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  MarktRoute: typeof MarktRoute
  ProduktRoute: typeof ProduktRoute
  ProduktTwoRoute: typeof ProduktTwoRoute
  UnternehmenRoute: typeof UnternehmenRouteWithChildren
  ApiIngestRoute: typeof ApiIngestRoute
  ApiPublicLatestRoute: typeof ApiPublicLatestRoute
  ApiPublicSensorRoute: typeof ApiPublicSensorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unternehmen': {
      id: '/unternehmen'
      path: '/unternehmen'
      fullPath: '/unternehmen'
      preLoaderRoute: typeof UnternehmenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produkt-two': {
      id: '/produkt-two'
      path: '/produkt-two'
      fullPath: '/produkt-two'
      preLoaderRoute: typeof ProduktTwoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produkt': {
      id: '/produkt'
      path: '/produkt'
      fullPath: '/produkt'
      preLoaderRoute: typeof ProduktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markt': {
      id: '/markt'
      path: '/markt'
      fullPath: '/markt'
      preLoaderRoute: typeof MarktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unternehmen/': {
      id: '/unternehmen/'
      path: '/'
      fullPath: '/unternehmen/'
      preLoaderRoute: typeof UnternehmenIndexRouteImport
      parentRoute: typeof UnternehmenRoute
    }
    '/unternehmen/team': {
      id: '/unternehmen/team'
      path: '/team'
      fullPath: '/unternehmen/team'
      preLoaderRoute: typeof UnternehmenTeamRouteImport
      parentRoute: typeof UnternehmenRoute
    }
    '/api/ingest': {
      id: '/api/ingest'
      path: '/api/ingest'
      fullPath: '/api/ingest'
      preLoaderRoute: typeof ApiIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sensor': {
      id: '/api/public/sensor'
      path: '/api/public/sensor'
      fullPath: '/api/public/sensor'
      preLoaderRoute: typeof ApiPublicSensorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/latest': {
      id: '/api/public/latest'
      path: '/api/public/latest'
      fullPath: '/api/public/latest'
      preLoaderRoute: typeof ApiPublicLatestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface UnternehmenRouteChildren {
  UnternehmenTeamRoute: typeof UnternehmenTeamRoute
  UnternehmenIndexRoute: typeof UnternehmenIndexRoute
}

const UnternehmenRouteChildren: UnternehmenRouteChildren = {
  UnternehmenTeamRoute: UnternehmenTeamRoute,
  UnternehmenIndexRoute: UnternehmenIndexRoute,
}

const UnternehmenRouteWithChildren = UnternehmenRoute._addFileChildren(
  UnternehmenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  MarktRoute: MarktRoute,
  ProduktRoute: ProduktRoute,
  ProduktTwoRoute: ProduktTwoRoute,
  UnternehmenRoute: UnternehmenRouteWithChildren,
  ApiIngestRoute: ApiIngestRoute,
  ApiPublicLatestRoute: ApiPublicLatestRoute,
  ApiPublicSensorRoute: ApiPublicSensorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
